### ISSUE TITLE
Could you share the checkpoint

### ISSUE THREAD

**Issue by HitBadTrap** [L-Sun/LGTM#5]
from lgtm.dataset.HumanML3D import BodyPart_HumanML3D

# This tool is for decomposition of full body motion description. You need to get an API key from OpenAI
tool = BodyPartAnnotationTool(
    api_key="",
    base_url="https://api.openai.com/v1",
)

# Load LGTM
**model = LGTM.load_from_checkpoint(Path("./checkpoints/lgtm/checkpoints/epoch=196-val_loss=0.3769.ckpt"))**
model.freeze()

# This part-level dataset is for de-normalized data. But you can use it for generation
dataset = BodyPart_HumanML3D(
    HumanML3D(Path("third_packages/HumanML3D"), Path("data/glove"), "all"),
    Path("./third_packages/TMR/datasets/annotations/humanml3d/annotations.json"),
)

**Comment by L-Sun** [comment]
you can use `prepare_data_models.sh` to down load all required checkpoint. In the end of this script, you can find the LGTM checkpoibt download commands, or use this link https://drive.google.com/file/d/1r_baVr24sf1jnz1KPHFaPB-jfkkzS-Iy/view?usp=sharing
